import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "dist");

mkdirSync(outDir, { recursive: true });

// dark theme (dracula) — default
const dark = new StyleDictionary({
  source: [
    resolve(__dirname, "tokens/base.json"),
    resolve(__dirname, "tokens/dracula.json"),
    resolve(__dirname, "tokens/custom.json"),
  ],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: `${outDir}/`,
      prefix: "ss",
      files: [
        {
          destination: "dark.css",
          format: "css/variables",
          options: {
            selector: ':root, [data-theme="dark"]',
            outputReferences: true,
          },
        },
      ],
    },
    json: {
      transformGroup: "css",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens-dark.json",
          format: "json/flat",
        },
      ],
    },
  },
});

// light theme (alucard)
const light = new StyleDictionary({
  source: [
    resolve(__dirname, "tokens/base.json"),
    resolve(__dirname, "tokens/light.json"),
    resolve(__dirname, "tokens/custom.json"),
  ],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: `${outDir}/`,
      prefix: "ss",
      files: [
        {
          destination: "light.css",
          format: "css/variables",
          options: {
            selector: '[data-theme="light"]',
            outputReferences: true,
          },
        },
      ],
    },
    json: {
      transformGroup: "css",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens-light.json",
          format: "json/flat",
        },
      ],
    },
  },
});

// base tokens (non-themed) for js/ts exports
const base = new StyleDictionary({
  source: [
    resolve(__dirname, "tokens/base.json"),
    resolve(__dirname, "tokens/dracula.json"),
    resolve(__dirname, "tokens/custom.json"),
  ],
  platforms: {
    js: {
      transformGroup: "js",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens.js",
          format: "javascript/esm",
        },
      ],
    },
    ts: {
      transformGroup: "js",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens.d.ts",
          format: "typescript/es6-declarations",
        },
      ],
    },
  },
});

await Promise.all([
  dark.buildAllPlatforms(),
  light.buildAllPlatforms(),
  base.buildAllPlatforms(),
]);

// combine CSS files into single tokens.css
const darkCss = readFileSync(resolve(outDir, "dark.css"), "utf-8");
const lightCss = readFileSync(resolve(outDir, "light.css"), "utf-8");
writeFileSync(resolve(outDir, "tokens.css"), `${darkCss}\n${lightCss}`);

// merge json into single tokens.json
const darkJson = JSON.parse(
  readFileSync(resolve(outDir, "tokens-dark.json"), "utf-8"),
);
const lightJson = JSON.parse(
  readFileSync(resolve(outDir, "tokens-light.json"), "utf-8"),
);
writeFileSync(
  resolve(outDir, "tokens.json"),
  JSON.stringify({ dark: darkJson, light: lightJson }, null, 2),
);

// generate tailwind theme extension
const generateTailwindConfig = (tokens: Record<string, string>) => {
  const theme: Record<string, Record<string, string>> = {};

  for (const [key, value] of Object.entries(tokens)) {
    const parts = key.split("-");
    const prefix = parts[0];
    const rest = parts.slice(1).join("-");

    if (!theme[prefix]) theme[prefix] = {};
    theme[prefix][rest || "DEFAULT"] = `var(--ss-${key})`;
  }

  return theme;
};

const tailwindTheme = generateTailwindConfig(darkJson);
const tailwindContent = `// auto-generated by @shockstack/tokens — do not edit
export default ${JSON.stringify(tailwindTheme, null, 2)};
`;
writeFileSync(resolve(outDir, "tailwind.tokens.js"), tailwindContent);

console.log("tokens built successfully");
