import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "dist");

mkdirSync(outDir, { recursive: true });

const baseTokens = resolve(__dirname, "tokens/base.json");
const customTokens = resolve(__dirname, "tokens/custom.json");

const themes = [
  {
    name: "dark",
    source: "dracula.json",
    selector: ':root, [data-theme="dark"]',
  },
  {
    name: "light",
    source: "light.json",
    selector: '[data-theme="light"]',
  },
  {
    name: "nord",
    source: "nord.json",
    selector: '[data-theme="nord"]',
  },
  {
    name: "gruvbox",
    source: "gruvbox.json",
    selector: '[data-theme="gruvbox"]',
  },
  {
    name: "midnight",
    source: "midnight.json",
    selector: '[data-theme="midnight"]',
  },
  {
    name: "dawn",
    source: "dawn.json",
    selector: '[data-theme="dawn"]',
  },
] as const;

const themedDictionaries = themes.map(
  (theme) =>
    new StyleDictionary({
      source: [
        baseTokens,
        resolve(__dirname, `tokens/${theme.source}`),
        customTokens,
      ],
      platforms: {
        css: {
          transformGroup: "css",
          buildPath: `${outDir}/`,
          prefix: "ss",
          files: [
            {
              destination: `${theme.name}.css`,
              format: "css/variables",
              options: {
                selector: theme.selector,
                outputReferences: true,
              },
            },
          ],
        },
        json: {
          transformGroup: "css",
          buildPath: `${outDir}/`,
          files: [
            {
              destination: `tokens-${theme.name}.json`,
              format: "json/flat",
            },
          ],
        },
      },
    }),
);

// base tokens (non-themed) for js/ts exports
const base = new StyleDictionary({
  source: [baseTokens, resolve(__dirname, "tokens/dracula.json"), customTokens],
  platforms: {
    js: {
      transformGroup: "js",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens.js",
          format: "javascript/esm",
        },
      ],
    },
    ts: {
      transformGroup: "js",
      buildPath: `${outDir}/`,
      files: [
        {
          destination: "tokens.d.ts",
          format: "typescript/es6-declarations",
        },
      ],
    },
  },
});

await Promise.all([
  ...themedDictionaries.map((dictionary) => dictionary.buildAllPlatforms()),
  base.buildAllPlatforms(),
]);

// combine CSS files into single tokens.css
const themeCss = themes
  .map((theme) => readFileSync(resolve(outDir, `${theme.name}.css`), "utf-8"))
  .join("\n");
writeFileSync(resolve(outDir, "tokens.css"), themeCss);

// merge all themed json outputs into single tokens.json
const tokensByTheme = Object.fromEntries(
  themes.map((theme) => [
    theme.name,
    JSON.parse(
      readFileSync(resolve(outDir, `tokens-${theme.name}.json`), "utf-8"),
    ),
  ]),
);
writeFileSync(
  resolve(outDir, "tokens.json"),
  JSON.stringify(tokensByTheme, null, 2),
);

// generate tailwind theme extension
const generateTailwindConfig = (tokens: Record<string, string>) => {
  const theme: Record<string, Record<string, string>> = {};

  for (const [key, value] of Object.entries(tokens)) {
    const parts = key.split("-");
    const prefix = parts[0];
    const rest = parts.slice(1).join("-");

    if (!theme[prefix]) theme[prefix] = {};
    theme[prefix][rest || "DEFAULT"] = `var(--ss-${key})`;
  }

  return theme;
};

const defaultThemeTokens = tokensByTheme.dark as Record<string, string>;
const tailwindTheme = generateTailwindConfig(defaultThemeTokens);
const tailwindContent = `// auto-generated by @shockstack/tokens — do not edit
export default ${JSON.stringify(tailwindTheme, null, 2)};
`;
writeFileSync(resolve(outDir, "tailwind.tokens.js"), tailwindContent);

console.log("tokens built successfully");
